### ISSUE TITLE
Issues with the NDBC Data Download

### ISSUE THREAD

**Issue by mishranurag** [timcera/tsgettoolbox#24]
Hi

I am trying to download the historical ndbc data and I always get the error that it is a BadGzipFile.

My code is

`df=tsgettoolbox.ndbc(station='pfdc1',table='ocean',startUTC='2020-01-01', endUTC='2020-05-01')`

The error is
`      BadGzipFile: Not a gzipped file (b'<!')`

Thank You
~A

**Comment by timcera** [comment]
Fixed in version 23.26.3.  Thanks Anurag!

Even when fixed, there is no "ocean" data for this station.  There is some "stdmet" data however.
