### ISSUE TITLE
ldas_nldas_fora high I/O processing or your IP address error

### ISSUE THREAD

**Issue by tbongiov** [timcera/tsgettoolbox#29]
I was downloading a bunch of NLDAS data and I was running into an inconsistent error. 

Example code

        tsget.ldas_nldas_fora(
            lat=29.3125,
            lon=-81.6875,
            variables=[
                "NLDAS_FORA0125_H.002:DLWRFsfc",
                "NLDAS_FORA0125_H.002:DSWRFsfc",
                "NLDAS_FORA0125_H.002:PEVAPsfc",
                "NLDAS_FORA0125_H.002:SPFH2m",         
                "NLDAS_FORA0125_H.002:TMP2m",
            ],
            startDate=str(datetime(1979, 1, 1, 0, 0)),
        )

If I printed out the resp variable I would receive this message
“This server is temporarily unable to service your request due to either high I/O processing or your IP address has reached the limit of concurrent connections. Please review/reduce the number of concurrent connections you are submitting, and try again.\r\nIf you feel you have received this message in error, please contact <a href="mailto:gsfc-help-disc@lists.nasa.gov"> GES DISC user services”

When I added the max_workers argument=1, then the error went away.  Looking into the ar.retrieve_binary function, max_workers defaults to 8. 
resp = ar.retrieve_binary(urls, kwds,max_workers=1)

Let me know what you think about this change.

**Comment by timcera** [comment]
I think that is a great idea. Do you have a sense about whether everything would still work with set to 2 or 4?  Or does it even matter?

**Comment by timcera** [comment]
I'll change it to 1 sometime this weekend and roll out a new release.  Kind of like the tortoise and the hare story.  Better that it works reliably than it goes real fast and fails.

**Comment by timcera** [comment]
Fixed in version 25.1.3
