### ISSUE TITLE
Issue with nwis instantaneous value

### ISSUE THREAD

**Issue by mishranurag** [timcera/tsgettoolbox#30]
I am seeing the following error when downloading the instantaneous values.

"Cannot infer dst time from 2019-11-03 01:00:00, try using the 'ambiguous' argument" Depending upon the USGS station, this date changes.

Sincerely
~A

**Comment by timcera** [comment]
Fixed in version 25.1.6.  I set the ambiguous DST fall transition to DST, and removed the duplicate value the DST transition causes in the spring.

Thank you for the report!

Kind regards,
Tim
