### ISSUE TITLE
Go through requirements

### ISSUE THREAD

**Issue by timcera** [timcera/tsgettoolbox#5]
odo has requirement for networkx > 1 and < 2.  Looking at the odo code it supports seamlessly either, so change in 'setup.py'.

**Comment by mishranurag** [comment]
I tried installing tsgetoolbox today and cam across the network issue.

    tsgettoolbox 20.41.11.21 has requirement networkx<2.0, but you'll have networkx 2.2 which is incompatible.

**Comment by mishranurag** [comment]
I downgraded my networkx and that worked.

**Comment by timcera** [comment]
Changed in ba1dc7f813424164c61467718193d28d57544bfe and fixed in latest version of tsgettoolbox.
